# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 044d9ca71d419adab60dcc0c49418a7efed1277d836e7c75e8ed92fe6f18be6c536db34837bbae9ec2ffa00f28f7713b304ff41460af31a70cc39d564b9856d5

test:
  secret_key_base: fb0931218fc4e38547382d29c048c88d7dfc1a617ccde41e413a97b08ece9eab98368bbd93a0aadd4f5e297c7aee38b06c0641ba060a9637d182476664a6f7b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
